
export const institutionCategories = [
    { id: 'all', label: 'All' },
    { id: 'varsity', label: 'University' },
    { id: 'engineering', label: 'Engineering' },
    { id: 'medical', label: 'Medical' },
];

// File: lib/institutions-data.ts

export const allInstitutions = [
    { id: 'du', title: 'ঢাকা বিশ্ববিদ্যালয়', shortName: 'DU', category: 'varsity' },
    { id: 'ru', title: 'রাজশাহী বিশ্ববিদ্যালয়', shortName: 'RU', category: 'varsity' },
    { id: 'cu', title: 'চট্টগ্রাম বিশ্ববিদ্যালয়', shortName: 'CU', category: 'varsity' },
    { id: 'ju', title: 'জাহাঙ্গীরনগর বিশ্ববিদ্যালয়', shortName: 'JU', category: 'varsity' },
    { id: 'ku', title: 'খুলনা বিশ্ববিদ্যালয়', shortName: 'KU', category: 'varsity' }, // ✅ Added KU
    { id: 'bup', title: 'BUP', shortName: 'BUP', category: 'varsity' },
    { id: 'gst', title: 'GST - গুচ্ছ (বিজ্ঞান)', shortName: 'GST', category: 'varsity' },
    { id: 'sust', title: 'SUST - শাবিপ্রবি', shortName: 'SUST', category: 'varsity' },
    { id: 'jnu', title: 'JNU - জগন্নাথ বিশ্ববিদ্যালয়', shortName: 'JNU', category: 'varsity' },
    { id: 'bsmrmu', title: 'BSMRMU', shortName: 'BSMRMU', category: 'varsity' },
    
    // Engineering
    { id: 'buet', title: 'BUET - বুয়েট', shortName: 'BUET', category: 'engineering' },
    { id: 'ruet', title: 'RUET - রুয়েট', shortName: 'RUET', category: 'engineering' },
    { id: 'kuet', title: 'KUET - কুয়েট', shortName: 'KUET', category: 'engineering' },
    { id: 'cuet', title: 'CUET - চুয়েট', shortName: 'CUET', category: 'engineering' },
    { id: 'ckruet', title: 'CKRUET (Combined)', shortName: 'CKRUET', category: 'engineering' },
    { id: 'butex', title: 'BUTEX', shortName: 'BUTEX', category: 'engineering' },
    { id: 'iut', title: 'IUT - ইসলামিক ইউনিভার্সিটি অফ টেকনোলজি', shortName: 'IUT', category: 'engineering' },
    { id: 'mist', title: 'MIST', shortName: 'MIST', category: 'engineering' },

    // Medical
    { id: 'medical', title: 'Medical', shortName: 'Medical', category: 'medical' },
    { id: 'dental', title: 'Dental', shortName: 'Dental', category: 'medical' },
    { id: 'afmc', title: 'AFMC', shortName: 'AFMC', category: 'medical' },
    { id: 'agri-gst', title: 'Agri - কৃষি গুচ্ছ', shortName: 'Agri-GST', category: 'medical' },

    // ✅ Added Missing Agricultural Universities
    { id: 'bau', title: 'বাংলাদেশ কৃষি বিশ্ববিদ্যালয়', shortName: 'BAU', category: 'medical' }, 
    { id: 'sau', title: 'শেরেবাংলা কৃষি বিশ্ববিদ্যালয়', shortName: 'SAU', category: 'medical' },
    { id: 'bsmrau', title: 'বঙ্গবন্ধু শেখ মুজিবুর রহমান কৃষি বিশ্ববিদ্যালয়', shortName: 'BSMRAU', category: 'medical' },
    { id: 'cvasu', title: 'চট্টগ্রাম ভেটেরিনারি ও এনিম্যাল সায়েন্সেস বিশ্ববিদ্যালয়', shortName: 'CVASU', category: 'medical' },
    { id: 'sylau', title: 'সিলেট কৃষি বিশ্ববিদ্যালয়', shortName: 'SYLAU', category: 'medical' },
];

export const unitData: Record<string, { name: string; logoId: string; years: string[] }> = {
    'du-a': { name: 'DU - A Unit (Science)', logoId: 'inst-du', years: ['2022-23', '2021-22', '2020-21', '2019-20', '2018-19', '2017-18', '2016-17', '2015-16'] },
    'du-b': { name: 'DU - B Unit (Arts)', logoId: 'inst-du', years: ['2022-23', '2021-22', '2020-21', '2019-20'] },
    'du-c': { name: 'DU - C Unit (Commerce)', logoId: 'inst-du', years: ['2022-23', '2021-22', '2020-21', '2019-20'] },
    'du-d': { name: 'DU - D Unit (Combined)', logoId: 'inst-du', years: ['2022-23', '2021-22', '2020-21', '2019-20'] },
    'ru-a': { name: 'RU - A Unit (Arts)', logoId: 'inst-ru', years: ['2022-23', '2021-22', '2020-21'] },
    'ru-b': { name: 'RU - B Unit (Commerce)', logoId: 'inst-ru', years: ['2022-23', '2021-22', '2020-21'] },
    'ru-c': { name: 'RU - C Unit (Science)', logoId: 'inst-ru', years: ['2022-23', '2021-22', '2020-21'] },
    'cu-a': { name: 'CU - A Unit (Science)', logoId: 'inst-cu', years: ['2022-23', '2021-22', '2020-21'] },
    'cu-b': { name: 'CU - B Unit (Arts)', logoId: 'inst-cu', years: ['2022-23', '2021-22', '2020-21'] },
    'cu-c': { name: 'CU - C Unit (Commerce)', logoId: 'inst-cu', years: ['2022-23', '2021-22', '2020-21'] },
    'cu-d': { name: 'CU - D Unit (Combined)', logoId: 'inst-cu', years: ['2022-23', '2021-22', '2020-21'] },
    'ku-a': { name: 'KU - A Unit (Science)', logoId: 'inst-ku', years: ['2022-23', '2021-22'] },
    'ku-b': { name: 'KU - B Unit (Arts)', logoId: 'inst-ku', years: ['2022-23', '2021-22'] },
    'ku-c': { name: 'KU - C Unit (Commerce)', logoId: 'inst-ku', years: ['2022-23', '2021-22'] },
    'ku-d': { name: 'KU - D Unit (Fine Arts)', logoId: 'inst-ku', years: ['2022-23', '2021-22'] },
    'ju-a': { name: 'JU - A Unit (Math & Physics)', logoId: 'inst-ju', years: ['2022-23', '2021-22', '2020-21'] },
    'ju-b': { name: 'JU - B Unit (Social Science)', logoId: 'inst-ju', years: ['2022-23', '2021-22', '2020-21'] },
    'ju-c': { name: 'JU - C Unit (Arts)', logoId: 'inst-ju', years: ['2022-23', '2021-22', '2020-21'] },
    'ju-d': { name: 'JU - D Unit (Biology)', logoId: 'inst-ju', years: ['2022-23', '2021-22', '2020-21'] },
    'ju-e': { name: 'JU - E Unit (Business)', logoId: 'inst-ju', years: ['2022-23', '2021-22', '2020-21'] },
    'ju-h': { name: 'JU - H Unit (IIT)', logoId: 'inst-ju', years: ['2022-23', '2021-22', '2020-21'] },
    'sust-a': { name: 'SUST - A Unit (Science)', logoId: 'inst-sust', years: ['2021-22', '2020-21'] },
    'sust-b': { name: 'SUST - B Unit (Combined)', logoId: 'inst-sust', years: ['2021-22', '2020-21'] },
    'jnu-a': { name: 'JNU - A Unit (Science)', logoId: 'inst-jnu', years: ['2021-22', '2020-21'] },
    'jnu-b': { name: 'JNU - B Unit (Arts)', logoId: 'inst-jnu', years: ['2021-22', '2020-21'] },
    'jnu-c': { name: 'JNU - C Unit (Commerce)', logoId: 'inst-jnu', years: ['2021-22', '2020-21'] },
    'jnu-d': { name: 'JNU - D Unit (Combined)', logoId: 'inst-jnu', years: ['2021-22', '2020-21'] },
    'buet': { name: 'BUET', logoId: 'inst-buet', years: ['2022-23', '2021-22', '2020-21', '2019-20', '2018-19'] },
    'medical': { name: 'Medical', logoId: 'inst-medical', years: ['2023', '2022', '2021', '2020', '2019', '2018'] },
    'guccho-science': { name: 'GST - A Unit (Science)', logoId: 'inst-guccho', years: ['2022-23', '2021-22'] },
    'guccho-arts': { name: 'GST - B Unit (Arts)', logoId: 'inst-guccho', years: ['2022-23', '2021-22'] },
    'guccho-commerce': { name: 'GST - C Unit (Commerce)', logoId: 'inst-guccho', years: ['2022-23', '2021-22'] },
    'krishi-guccho': { name: 'Agri - কৃষি গুচ্ছ', logoId: 'inst-agri', years: ['2022-23', '2021-22', '2020-21'] },
    'kuet': { name: 'KUET', logoId: 'inst-kuet', years: ['2021-22', '2020-21', '2019-20'] },
    'ruet': { name: 'RUET', logoId: 'inst-ruet', years: ['2021-22', '2020-21', '2019-20'] },
    'cuet': { name: 'CUET', logoId: 'inst-cuet', years: ['2021-22', '2020-21', '2019-20'] },
    'ckruet': { name: 'CKRUET (Combined)', logoId: 'inst-guccho-eng', years: ['2022-23', '2021-22'] },
    'bup-fst': { name: 'BUP - FST (Science)', logoId: 'inst-bup', years: ['2022-23', '2021-22'] },
    'bup-fsss': { name: 'BUP - FSSS (Social Science)', logoId: 'inst-bup', years: ['2022-23', '2021-22'] },
    'bup-fass': { name: 'BUP - FASS (Arts)', logoId: 'inst-bup', years: ['2022-23', '2021-22'] },
    'bup-fbs': { name: 'BUP - FBS (Business)', logoId: 'inst-bup', years: ['2022-23', '2021-22'] },
    'bsmrmu': { name: 'Maritime', logoId: 'inst-maritime', years: ['2022-23', '2021-22'] },
    'dental': { name: 'Dental', logoId: 'inst-dental', years: ['2023', '2022', '2021'] },
    'afmc': { name: 'AFMC', logoId: 'inst-afmc', years: ['2023', '2022', '2021'] },
    'iut': { name: 'IUT - ইসলামিক ইউনিভার্সিটি অফ টেকনোলজি', logoId: 'inst-iut', years: ['2022-23', '2021-22', '2019-20'] },
    'bau': { name: 'BAU', logoId: 'inst-agri', years: ['2021-22', '2020-21'] },
    'sau': { name: 'SAU', logoId: 'inst-sau', years: ['2021-22', '2020-21'] },
    'bsmrau': { name: 'BSMRAU', logoId: 'inst-bsmrau', years: ['2021-22', '2020-21'] },
    'cvasu': { name: 'CVASU', logoId: 'inst-cvasu', years: ['2021-22', '2020-21'] },
    'sylau': { name: 'SYLAU', logoId: 'inst-sau-sylhet', years: ['2021-22', '2020-21'] },
};


export const institutionData: Record<string, { name: string; units: {id: string, name: string}[] }> = {
    du: { name: 'Dhaka University', units: [{id: 'du-a', name: 'A Unit (Science)'}, {id: 'du-b', name: 'B Unit (Arts)'}, {id: 'du-c', name: 'C Unit (Commerce)'}, {id: 'du-d', name: 'D Unit (Combined)'}] },
    ru: { name: 'Rajshahi University', units: [{id: 'ru-a', name: 'A Unit (Arts)'}, {id: 'ru-b', name: 'B Unit (Commerce)'}, {id: 'ru-c', name: 'C Unit (Science)'}] },
    cu: { name: 'Chittagong University', units: [{id: 'cu-a', name: 'A Unit (Science)'}, {id: 'cu-b', name: 'B Unit (Arts)'}, {id: 'cu-c', name: 'C Unit (Commerce)'}, {id: 'cu-d', name: 'D Unit (Combined)'}] },
    ku: { name: 'Khulna University', units: [{id: 'ku-a', name: 'A Unit (Science)'}, {id: 'ku-b', name: 'B Unit (Arts)'}, {id: 'ku-c', name: 'C Unit (Commerce)'}, {id: 'ku-d', name: 'D Unit (Fine Arts)'}] },
    ju: { name: 'Jahangirnagar University', units: [{id: 'ju-a', name: 'A Unit (Math & Physics)'}, {id: 'ju-b', name: 'B Unit (Social Science)'}, {id: 'ju-c', name: 'C Unit (Arts)'}, {id: 'ju-d', name: 'D Unit (Biology)'}, {id: 'ju-e', name: 'E Unit (Business)'}, {id: 'ju-h', name: 'H Unit (IIT)'}] },
    sust: { name: 'SUST', units: [{id: 'sust-a', name: 'A Unit (Science)'}, {id: 'sust-b', name: 'B Unit (Combined)'}] },
    jnu: { name: 'Jagannath University', units: [{id: 'jnu-a', name: 'A Unit (Science)'}, {id: 'jnu-b', name: 'B Unit (Arts)'}, {id: 'jnu-c', name: 'C Unit (Commerce)'}, {id: 'jnu-d', name: 'D Unit (Combined)'}] },
    bup: { name: 'BUP', units: [{id: 'bup-fst', name: 'FST (Science)'}, {id: 'bup-fsss', name: 'FSSS (Social Science)'}, {id: 'bup-fass', name: 'FASS (Arts)'}, {id: 'bup-fbs', name: 'FBS (Business)'}] },
    gst: { name: 'GST', units: [{id: 'guccho-science', name: 'A Unit (Science)'}, {id: 'guccho-arts', name: 'B Unit (Arts)'}, {id: 'guccho-commerce', name: 'C Unit (Commerce)'}] },
    buet: { name: 'BUET', units: [{id: 'buet', name: 'Engineering'}] },
    medical: { name: 'Medical', units: [{id: 'medical', name: 'MBBS'}] },
    dental: { name: 'Dental', units: [{id: 'dental', name: 'BDS'}] },
    afmc: { name: 'AFMC', units: [{id: 'afmc', name: 'AFMC'}] },
    'agri-gst': { name: 'Agriculture GST', units: [{id: 'krishi-guccho', name: 'Agri GST'}]},
    ruet: { name: 'RUET', units: [{id: 'ruet', name: 'Engineering'}] },
    kuet: { name: 'KUET', units: [{id: 'kuet', name: 'Engineering'}] },
    cuet: { name: 'CUET', units: [{id: 'cuet', name: 'Engineering'}] },
    ckruet: { name: 'CKRUET', units: [{id: 'ckruet', name: 'Engineering'}] },
    butex: { name: 'BUTEX', units: [{id: 'butex', name: 'Textile Engineering'}] },
    iut: { name: 'IUT', units: [{id: 'iut', name: 'Engineering & BBA'}] },
    mist: { name: 'MIST', units: [{id: 'mist', name: 'Engineering'}] },
    bsmrmu: { name: 'BSMRMU', units: [{id: 'maritime', name: 'Maritime'}] },
    bau: { name: 'BAU', units: [{id: 'bau', name: 'Agriculture'}]},
    sau: { name: 'SAU', units: [{id: 'sau', name: 'Agriculture'}]},
    bsmrau: { name: 'BSMRAU', units: [{id: 'bsmrau', name: 'Agriculture'}]},
    cvasu: { name: 'CVASU', units: [{id: 'cvasu', name: 'Veterinary'}]},
    sylau: { name: 'SYLAU', units: [{id: 'sylau', name: 'Agriculture'}]},
};
